#!/bin/bash
#text format and color
BOLD='\e[1m';
RED='\e[31m'
GREEN='\e[32m'
NC='\e[39m' # No Color
printf '
  _____            __       _______
 / ____|          / _|     |__   __|
| (___   ___ _ __| |_ ___     | | ___  __ _ _ __  ___
 \___ \ / _ \ `__|  _/ _ \    | |/ _ \/ _` | `_ `´_  \
 ____) |  __/ |  | ||  __/    | |  __/ (_| | | | | | |
|_____/ \___|_|  |_| \___|    |_|\___|\__,_|_| |_| |_|';

if [[ ( -n "$1" ) && ("$1"=="-h") ]]
then
  printf "${BOLD}webm2gif [filename]${NC}

filename: input filename without extension, for example if the video name is ${BOLD}my-awesome-video.webm${NC} then just type
  $ webm2gif my-awesome-video
you will find my-awesome-video.gif in the same folder than original video.

More options in https://hub.docker.com/r/jrottenberg/ffmpeg/
";
  exit 0;
fi

docker run --user=$UID:$UID -v $PWD:/temp/ jrottenberg/ffmpeg -stats  \
        -i "/temp/$1.webm" \
        -loop 1  \
        -final_delay 50 -c:v gif -f gif - > "$1.gif"
